### ISSUE TITLE
"Vehicle cannot be parked here"

### ISSUE THREAD

**Issue by jayyy299** [kasuganosoras/zerodream_parking#5]
I'm parking my vehicle in a global location and it tells me it can't be parked there after I exit my car.
Also the G doesn't work for the engine, I need to manually /engine.

**Comment by Alfita2021** [comment]
Check if the vehicle class is allowed. You can check this in the config.lua, in: allowTypes

**Comment by Alfita2021** [comment]
if you want to allow all types of vehicles, change: 
allowTypes = { 0, 1, 2, 2, 3, 4, 5 } 
to
allowTypes = { -1 }

**Comment by jayyy299** [comment]
That worked, but it doesn't save after a restart it returns to a parking lot if I park it elsewhere.

**Comment by Alfita2021** [comment]
> That worked, but it doesn't save after a restart it returns to a parking lot if I park it elsewhere.

You just have to modify a garage script, for example I modified lunar_garage (if you want I can share it) and modified the server.lua of the zerodream_parking,
In function ImpoundVehicle(player, plate) you have to change:
MySQL.Sync.execute('UPDATE owned_vehicles SET stored = https://github.com/stored WHERE plate = https://github.com/plate', {.
['https://github.com/stored'] = '0',
['https://github.com/plate'] = plate
})

to

MySQL.Sync.execute('UPDATE owned_vehicles SET stored = https://github.com/stored AND pound = @pound WHERE plate = https://github.com/plate', {
['https://github.com/stored'] = '0',
['@pound'] = '1',
['https://github.com/plate'] = plate
})

**Comment by Alfita2021** [comment]
> That worked, but it doesn't save after a restart it returns to a parking lot if I park it elsewhere.

You just have to modify a garage script, for example I modified lunar_garage (if you want I can share it) and modified the server.lua of the zerodream_parking,
In function ImpoundVehicle(player, plate) you have to change:
MySQL.Sync.execute('UPDATE owned_vehicles SET stored = @stored WHERE plate = @plate', {.
['@stored'] = '0',
['@plate'] = plate
})

to

MySQL.Sync.execute('UPDATE owned_vehicles SET stored = @stored AND pound = @pound WHERE plate = @plate', {
['@stored'] = '0',
['@pound'] = '1',
['@plate'] = plate
})

**Comment by Alfita2021** [comment]
> That worked, but it doesn't save after a restart it returns to a parking lot if I park it elsewhere.

What version are you using? standalone or ESX?
Are you getting any errors?

**Comment by jayyy299** [comment]
Standalone, there's no errors but I fixed it thanks for the help with the parking issue! I appreciate it.

The parking wouldn't save because the config had a missing bracket }
